url: https://repo.toogoodbruh.com   # with the https protocol
enforce_ssl: repo.toogoodbruh.com   # without any protocol

# For example, my configuration is this:
url: https://toogoodbruh.com
enforce_ssl: toogoodbruh.com
