#!/bin/sh
mkdir -p /var/mobile/Library/Caches
chmod 777 /var/mobile/Library/Caches
chown mobile /var/mobile/Library/Caches
touch /var/mobile/Library/Caches/libactivator.plist
chmod 666 /var/mobile/Library/Caches/libactivator.plist
chown mobile /var/mobile/Library/Caches/libactivator.plist
rm -f /Library/MobileSubstrate/DynamicLibraries/Activator.disabled
( launchctl stop com.apple.mobilegestalt.xpc 2> /dev/null && launchctl start com.apple.mobilegestalt.xpc ) || true
( launchctl stop com.apple.wcd 2> /dev/null && launchctl start com.apple.wcd 2> /dev/null ) || true
exec activator postinst
